name: Build and Deploy Javascript Documents

on:
  push:
    branches:
      - main

jobs:
  deploy-developer-hub:
    defaults:
      run:
        working-directory: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci

  deploy-gh-pages-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # Build javascript docs
      - run: |
          cd ./ldk/javascript
          npm ci
          npm run build
          npm run doc

      # Consolidate docs
      - run: |
          cd ./ldk
          mkdir typedoc-tmp
          cp -r ./javascript/docs typedoc-tmp/javascript
          cp -r ./javascript/readme_assets typedoc-tmp/javascript

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./ldk/typedoc-tmp
          destination_dir: ldk
          force_orphan: true
